let janetGrammar = {
	"frozenYogurt": ["Try out our newest flavors: #normalFlavor# and #weirdFlavor#!", "Have you ever tried #weirdFlavor#? It goes really well with #normalFlavor#.", "How about #normalFlavor# and #weirdFlavor#?"],
	"normalFlavor": ["Cherry", "Raspberry Sorbet", "Sweet Potato Fries", "Double Rainbow", "Bubblegum", "Cookies \\'n\\' Cream"],
	"weirdFlavor": ["Sleeping in on a Rainy Sunday", "Mother\\'s Love", "Mars Landing", "Baby Kittens", "Technological Breakthrough", "Satisfying TV Finale", "Fast Wi-Fi", "Beautiful Music"],
	"restuarant": ["Would you like a warm bowl of soup? Try out #soup#!", "Would you like a nice meal with your soulmate? Make reservations at #meal#!", "Want some snacks? checkout #snack#!"],
	"snack": ["Knish From a Rose", "Biscotti Pippen", "Hot dog on a stick", "Cruller intentions"],
	"meal": ["Sushi and the banshees", "Caviar on a stick", "Lasagne Come Out Tomorrow"],
	"soup": ["Mmmmmm! Chowder Fountain", "Chicken Soup For The Mouth"],
	"time": ["It\\'s #JeremyBearimy# on the Jeremy Bearimy timeline."],
	"JeremyBearimy": ["the dot on the i", "the first e in Jeremy", "the left circle that connects J and y", "between y and B", "the a in Bearimy"],
	"points":[
		"sing to a child: +1",
		"end slavery: +814292",
		"remember sister\\'s birthday: +15",
		"purify water source: +295",
		"remain royal to cleveland browns: +53",
		"scratch elbow: +2",
		"step carefully over flower bed: +3",
		"fail you to disclose camel illness when selling camel: -22",
		"commit genocide: -433115",
		"tell a woman to smile: -53",
		"ruin opera with boorish behavior: -90",
		"overstate personal connection to tragedy that has nothing to do with you: -40",
		"posion a river: -4010"
	],
	"eleanor":["This is how I alaways got out of escape rooms. If you break enough stuff, they open the door and kick you out.",
							"Ya basic!",
							"Why do bad things always happen to mediocre people who are lying about their identities?",
							"It\\'s suddenly very important that I get drunk.",
							"This doodle of a burrito because when I first read Aristotle, I thought it was pronounced like Chipotle.",
							"Girl, you\\'re a messy bench who loves drama and I am into it.",
							"Pobody’s nerfect.",
							"When I told a boyfriend something was ‘no big deal,’ it meant anything from ‘I just bought weed from your nephew,’ to ‘I secretly befriended your ex-girlfriend last year, things got out of hand, and now I’m her bridesmaid.\\'"],
	"chidi": ["So, making decisions isn\\'t necessarily my strong suit.",
						"Well, I\\'ve narrowed it down to two possibilities: yes and no.",
						"If this isn’t a test, then it’s something way worse: A choice! That we have to make!",
						"You know the sound a fork makes in the garbage disposal? That’s the sound my brain makes. All the time. It’s just the constant grinding about things that I’m afraid of or things that I want or want to want, or want to want to want.",
					],
	"tahani": ["I just want to sit and stare at nothing.",
						"You know, sometimes a flaw can make something even more beautiful. Like with Cindy Crawford and how short she is.",
						"Maybe I should try to be silent too. No really. Look, here I go. Uh, that was wonderful. So cleansing!",
						"We can do this but we must remain emotionless, I\\'m talking Kristen Stewart on a red carpet level of emtionless here.",
						"I’m not used to dressing like a plumberess. Is that what you call a female plumber or is a toilet sweep or, or clog wench?"
						],
	"jason": ["I have no idea what\\'s going on, but everyone is talking and I should, too.",
						"I can\\'t go, I\\'m too young to die and too old to eat off the kids\\' menu. What a stupid age I am.",
						"You know, it doesn\\'t matter if you know things, all that matters is what\\'s in your heart.",
						"I wasn’t a failed DJ. I was pre-successful.",
						"I’m ranking my favourite Fast and the Furious movies. You said you wanted to know who I am, and this is the best way to get to know me.",
						"When I say I’m meditating, I’m just trying to figure out what the fork is happening."],
	"michael": ["Parties are mere distractions from the relentlessness of entropy. We\\'re all just corpses who haven\\'t yet begun to decay.",
							"Any place or thing in the universe can be up to 104% perfect. That\\'s how you got Beyonce.",
							"Now we\\'re going to do the most human thing of all: attemp something futile with a ton of unearned confidence and fail spectacularly!",
							"You died alone because you couldn\\'t commit to anyone.",
							"You humans take something wonderful and ruin it just a little bit so you can have more.",
							"I studied the human concept of friends. I even watched all ten seasons of the show Friends. Boy, those friends really were ‘friends’, weren’t they? Although – and I realise this is the kind of observation that would only occur to the mind of an eternal being. How did they afford that apartment? A waitress and a chef with those Manhattan real estate prices.",
							"In the words of one of my actual friends: ‘Ya basic’. It’s a human insult. It’s devastating. You’re devastated right now."],
	"shawn": ["I just want to go back to my container of goo and go to sleep.",
						"Fair is the stupidest word humans ever invented, except for staycation.",
						"I have heard no statements nor seen any evidence to suggest... oh he\\'s from Florida? Yeah he belongs to the bad place."],
	"lifeAdvice":
	[
	"Principles aren’t principles when you pick and choose when you’re gonna follow them.",
	"You’re cool, dope, fresh and smart-brained. I’ve never seen you dance, but I bet you’re good, ’cause you’re good at everything. You’re awesome! Be nicer to yourself.",
	"My whole life, whenever I encountered any obstacles, I would simply say, ‘I would like to speak to a manager.’ But in our relationship, there was no manager. There was no one who could fix this for me except me.",
	"In case you were wondering, I am, by definition, the best version of myself.",
	"I argue that we choose to be good because of our bonds with other people and our innate desire to treat them with dignity. Simply put, we are not in this alone.",
	"What matters isn’t if people are good or bad. What matters is, if they’re trying to be better today than they were yesterday. You asked me where my hope comes from? That’s my answer.",
	"Where I’m from, most things blow up eventually. So I learned that when something dope comes along, you gotta lock it down! If you’re always frozen in fear and taking too long to figure out what to do, you’ll miss your opportunity, and maybe get sucked into the propeller of a swamp boat.",
	"If soulmates do exist, they’re not found. They’re made.",
	"You said that every human is a little bit sad all the time, because you know you’re going to die. But that knowledge is what gives life meaning.",
	"This is what we’ve been looking for since the day we met. Time. That’s what the Good Place really is — it’s not even a place, really. It’s just having enough time with the people you love."
	]
}
